services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=lectors'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - "5437:5432"
    networks:
      - mynetwork
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lectors
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/lectors
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_FLYWAY_PASSWORD=root
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
      - postgres
    ports:
      - '8130:8130'
    external_links:
      - eureka-server:eureka-server
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true